// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CreateRoom(arg1) {
  return window['go']['main']['App']['CreateRoom'](arg1);
}

export function GenerateRandomPersona() {
  return window['go']['main']['App']['GenerateRandomPersona']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendAudienceAction(arg1) {
  return window['go']['main']['App']['SendAudienceAction'](arg1);
}

export function StartBattle() {
  return window['go']['main']['App']['StartBattle']();
}

export function StopBattle() {
  return window['go']['main']['App']['StopBattle']();
}
