// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {battle} from '../models';

export function Bootstrap():Promise<battle.BootstrapData>;

export function CreateRoom(arg1:battle.RoomConfigInput):Promise<battle.RoomState>;

export function GenerateRandomPersona():Promise<battle.PersonaConfig>;

export function GetSettings():Promise<battle.AppSettings>;

export function GetState():Promise<battle.RoomState>;

export function SaveSettings(arg1:battle.AppSettings):Promise<battle.AppSettings>;

export function SendAudienceAction(arg1:battle.AudienceActionInput):Promise<battle.RoomState>;

export function StartBattle():Promise<battle.RoomState>;

export function StopBattle():Promise<battle.RoomState>;
